[tool.poetry]
name = "pente-engine"
version = "0.1.0"
description = "Pente Board Game Engine"
authors = ["Dan Turch"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
